variables:
  controller_actions: &controller_actions #Dictionary of actions/buttons on remote controller
    - label: "1. Turn on"
      value: TURN_ON
    - label: "2. Turn off"
      value: TURN_OFF
    - label: "3. Scene 1 (one square)"
      value: SCENE_1
    - label: "4. Scene 2 (two squares)"
      value: SCENE_2
    - label: "5. Scene 3 (three squares)"
      value: SCENE_3
    - label: "6. Scene 4 (four squares)"
      value: SCENE_4
    - label: "7. Dim up (right up)"
      value: "DIM_UP"
    - label: "8. Dim up (right up - long press)"
      value: "DIM_UP_LP"
    - label: "9. Dim down (right down)"
      value: "DIM_DOWN"
    - label: "10. Dim down (right down - long press)"
      value: "DIM_DOWN_LP"
    - label: "11. Color up (D-pad up with red LED)"
      value: "COLOR_UP"
    - label: "12. Color up (D-pad up with red LED - long press)"
      value: "COLOR_UP_LP"
    - label: "13. Color down (D-pad down with red LED)"
      value: "COLOR_DOWN"
    - label: "14. Color down (D-pad down with red LED - long press)"
      value: "COLOR_DOWN_LP"
    - label: "15. Saturation up (D-pad up with green LED)"
      value: "SATURATION_UP"
    - label: "16. Saturation up (D-pad up with green LED - long press)"
      value: "SATURATION_UP_LP"
    - label: "17. Saturation down (D-pad down with green LED"
      value: "SATURATION_DOWN"
    - label: "18. Saturation down (D-pad down with green LED - long press)"
      value: "SATURATION_DOWN_LP"
    - label: "19. Hue left (D-pad left with green LED)"
      value: "HUE_LEFT"
    - label: "20. Hue right (D-pad right with green LED)"
      value: "HUE_RIGHT"


blueprint:
  name: Zigbee2MQTT Adeo LXEK-5/ZBEK-26 v1.3.0
  description: |
    Control various devices with the Adeo LXEK-5/ZBEK-26 (Leroy Merlin - Lexman) remote connected via Zigbee2MQTT
    HR-C99C-Z-C045 - https://zigbee.blakadder.com/ADEO_HR-C99C-Z-C045.html - https://www.zigbee2mqtt.io/devices/HR-C99C-Z-C045.html
    ![Device Image](https://github.com/SirYasko/HA-Blueprints/raw/main/zha-adeo-lxek5-zbek26.png)
  source_url: https://github.com/SirYasko/HA-Blueprints/blob/main/zha-adeo-lxek5-zbek26-btn.yaml
  domain: automation
  author: SirYasko - SoaR245
  homeassistant:
    min_version: 2024.6.0

  input:
    section_debug:
      name: "## Debugging and error detection"
      icon: mdi:bug-outline
      description: "Enable when you know what you're doing - helpful for error detection and debugging"
      collapsed: true
      input:
        i__debug_f:
          name: (Required) Send debug notifications to HA
          description: Disabled by default
          default: false
          selector:
            boolean:

        i__debug_button:
          name: "Simulate a button press"
          description: ""
          selector:
           select:
              mode: dropdown
              options: *controller_actions
          default: null

    i__remote:
      name: (Required) Adeo LXEK-5/ZBEK-26 remote controller
      description: Select the remote controller you wish to use.
      selector:
        device:
          filter:
            - integration: mqtt
              model: RGB CTT LEXMAN ENKI remote control

    section_onoff:
      name: "## Configuration - on / off"
      icon: mdi:power
      description: ""
      collapsed: false
      input:

        i__action_button_on:
          name: (Optional) Action for [Turn on] button
          description: "I button"
          selector:
            action: {}
          default: []

        i__action_button_off:
          name: (Optional) Action for [Turn off] button
          description: "O button"
          selector:
            action: {}
          default: []

    section_scenes:
      name: "## Configuration - scenes"
      description: ""
      icon: mdi:numeric-4-box-multiple-outline
      collapsed: false
      input:

        i__action_button_scene_1:
          name: (Optional) Action for [Scene 1] button
          description: |
            &#x25A0;
          selector:
            action: {}
          default: []

        i__action_button_scene_2:
          name: (Optional) Action for [Scene 2] button
          description: |
            &#x25A0;
            &#x25A0;
          selector:
            action: {}
          default: []

        i__action_button_scene_3:
          name: (Optional) Action for [Scene 3] button
          description: |
            &#x25A0;&nbsp;&ensp;&#x25A0;
            &#x25A0;
          selector:
            action: {}
          default: []

        i__action_button_scene_4:
          name: (Optional) Action for [Scene 4] button
          description: |
            &#x25A0;&nbsp;&ensp;&#x25A0;
            &#x25A0;&nbsp;&ensp;&#x25A0;
          selector:
            action: {}
          default: []

    section_dimmer:
      name: "## Configuration - dimmer"
      description: ""
      icon: mdi:menu-swap-outline
      collapsed: false
      input:

        i__action_button_dim_up:
          name: (Optional) Action for [Dim up] button
          description: "▲ - up button on the right"
          selector:
            action: {}
          default: []

        i__action_button_dim_down:
          name: (Optional) Action for [Dim down] button
          description: "▼ - down button on the right"
          selector:
            action: {}
          default: []

    section_dpad:
      name: "## Configuration - d-pad"
      description: ""
      icon: mdi:gamepad-outline
      collapsed: false
      input:

        i__action_button_color_up:
          name: (Optional) Action for [Color up] button
          description: "▲ ▲ D-pad up with red LED"
          selector:
            action: {}
          default: []

        i__action_button_color_down:
          name: (Optional) Action for [Color down] button
          description: "▼ ▼ D-pad down with red LED"
          selector:
            action: {}
          default: []

        i__action_button_saturation_up:
          name: (Optional) Action for [Saturation up] button
          description: "▲ ▲ D-pad up with green LED"
          selector:
            action: {}
          default: []

        i__action_button_saturation_down:
          name: (Optional) Action for [Saturation down] button
          description: "▼ ▼ D-pad down with green LED"
          selector:
            action: {}
          default: []

        i__action_button_hue_left:
          name: (Optional) Action for [Hue left] button
          description: "◄ ◄ D-pad left with green LED"
          selector:
            action: {}
          default: []

        i__action_button_hue_right:
          name: (Optional) Action for [Hue right] button
          description: "► ► D-pad right with green LED"
          selector:
            action: {}
          default: []


mode: restart
max_exceeded: silent


triggers:
  # triggers for zigbee2mqtt mqtt device action
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'on'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'off'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'scene_1'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'scene_2'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'scene_3'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'scene_4'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'brightness_step_up'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'brightness_step_down'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'color_temperature_step_up'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'color_temperature_step_down'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'color_saturation_step_up'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'color_saturation_step_down'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'color_hue_step_up'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'color_hue_step_down'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'color_stop'
  - trigger: device
    domain: mqtt
    device_id: !input i__remote
    type: action
    subtype: 'brightness_stop'

action:
- variables:
    v__payload:         '{% if trigger.payload is defined %} {{trigger.payload}} {% elif v__debug_button is not none %} debug_button {% endif %}'
    v__button_pressed: >      
      {% if   v__payload == "debug_button"                %}  {{ v__debug_button }}
      {% elif v__payload == "on"                          %}  TURN_ON
      {% elif v__payload == "off"                         %}  TURN_OFF
      {% elif v__payload == "scene_1"                     %}  SCENE_1
      {% elif v__payload == "scene_2"                     %}  SCENE_2
      {% elif v__payload == "scene_3"                     %}  SCENE_3
      {% elif v__payload == "scene_4"                     %}  SCENE_4
      {% elif v__payload == "brightness_step_up"          %}  DIM_UP
      {% elif v__payload == "brightness_step_down"        %}  DIM_DOWN
      {% elif v__payload == "color_temperature_step_up"   %}  COLOR_UP
      {% elif v__payload == "color_temperature_step_down" %}  COLOR_DOWN
      {% elif v__payload == "color_saturation_step_up"    %}  SATURATION_UP
      {% elif v__payload == "color_saturation_step_down"  %}  SATURATION_DOWN
      {% elif v__payload == "color_hue_step_up"           %}  HUE_LEFT
      {% elif v__payload == "color_hue_step_down"         %}  HUE_RIGHT
      {% elif v__payload == "color_stop"                  %}  STOP
      {% elif v__payload == "brightness_stop"             %}  STOP
      {% else %}                                            UNKNOWN
      {% endif %}
    v__action_button_on:                   !input i__action_button_on
    v__action_button_off:                  !input i__action_button_off
    v__action_button_scene_1:              !input i__action_button_scene_1
    v__action_button_scene_2:              !input i__action_button_scene_2
    v__action_button_scene_3:              !input i__action_button_scene_3
    v__action_button_scene_4:              !input i__action_button_scene_4
    v__action_button_dim_up:               !input i__action_button_dim_up
    v__action_button_dim_down:             !input i__action_button_dim_down
    v__action_button_color_up:             !input i__action_button_color_up
    v__action_button_color_down:           !input i__action_button_color_down
    v__action_button_saturation_up:        !input i__action_button_saturation_up
    v__action_button_saturation_down:      !input i__action_button_saturation_down
    v__action_button_hue_right:            !input i__action_button_hue_right
    v__action_button_hue_left:             !input i__action_button_hue_left

# DEBUG
- choose:
  - conditions:
    - condition: template
      value_template: '{{ v__debug_f == true }}'
    sequence:
      - service: persistent_notification.create
        data:
          title: 'Parameters'
          message: |
             v__payload:                     {{v__payload                    }};
             v__button_pressed:              {{v__button_pressed             }};
             _________________________________________________________________
             v__action_button_on:              {{v__action_button_on              }};
             v__action_button_off:             {{v__action_button_off             }};
             v__action_button_scene_1:         {{v__action_button_scene_1         }};
             v__action_button_scene_2:         {{v__action_button_scene_2         }};
             v__action_button_scene_3:         {{v__action_button_scene_3         }};
             v__action_button_scene_4:         {{v__action_button_scene_4         }};
             v__action_button_dim_up:          {{v__action_button_dim_up          }};
             v__action_button_dim_down:        {{v__action_button_dim_down        }};
             v__action_button_color_up:        {{v__action_button_color_up        }};
             v__action_button_color_down:      {{v__action_button_color_down      }};
             v__action_button_saturation_up:   {{v__action_button_saturation_up   }};
             v__action_button_saturation_down: {{v__action_button_saturation_down }};
             v__action_button_hue_right:       {{v__action_button_hue_right       }};
             v__action_button_hue_left:        {{v__action_button_hue_left        }};

  default: []

- choose:

  #OFF
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "TURN_OFF" }}'
    sequence: !input i__action_button_off

  #ON
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "TURN_ON" }}'
    sequence: !input i__action_button_on

  #SCENE 1
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "SCENE_1" }}'
    sequence: !input i__action_button_scene_1

  #SCENE 2
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "SCENE_2" }}'
    sequence: !input i__action_button_scene_2

  #SCENE 3
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "SCENE_3" }}'
    sequence: !input i__action_button_scene_3

  #SCENE 4
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "SCENE_4" }}'
    sequence: !input i__action_button_scene_4

  #DIM_UP
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "DIM_UP" }}'
    sequence: !input i__action_button_dim_up

  #DIM_DOWN
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "DIM_DOWN" }}'
    sequence: !input i__action_button_dim_down

  #COLOR_UP
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "COLOR_UP" }}'
    sequence: !input i__action_button_color_up

  #COLOR_DOWN
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "COLOR_DOWN" }}'
    sequence: !input i__action_button_color_down

  #SATURATION_UP
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "SATURATION_UP" }}'
    sequence: !input i__action_button_saturation_up

  #SATURATION_DOWN
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "SATURATION_DOWN" }}'
    sequence: !input i__action_button_saturation_down

  #HUE_RIGHT
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "HUE_RIGHT" }}'
    sequence: !input i__action_button_hue_right

  #HUE_LEFT
  - conditions:
    - condition: template
      value_template: '{{ v__button_pressed == "HUE_LEFT" }}'
    sequence: !input i__action_button_hue_left

  default: []